name: RENEW
on:
  schedule:
    - cron: '0 0 1,15 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Import GPG
        uses: crazy-max/ghaction-import-gpg@v1.4.1
        with:
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true
          git_committer_name: Insouciant21
          git_committer_email: 48847364+Insouciant21@users.noreply.github.com
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      - name: Git commit
        run: |
          echo $(date +'%Y-%m-%d') >> ARS_File
          git config --global commit.gpgsign true
          git config --global user.email "48847364+Insouciant21@users.noreply.github.com"
          git config --global user.name "Insouciant21"
          git add .
          git commit -S -m "Keep active"
          git push
